import { type Card } from "@fiction-wars/shared-types";

// Stats are on a 0–100 scale, roughly balanced so no single character
// dominates every category — each one has a signature strength and a
// genuine weakness so stat-picking is a real decision, not just "pick ATK
// every round." Total stat variance is intentional.

export const SEED_CARDS: Omit<Card, "imageUrl">[] = [
  // ─── DC ──────────────────────────────────────────────────────────────
  {
    id: "superman-dc",
    name: "Superman",
    universe: "DC",
    stats: { atk: 97, def: 92, speed: 88, hp: 99 },
    accentColor: "#0032A0",
  },
  {
    id: "batman-dc",
    name: "Batman",
    universe: "DC",
    stats: { atk: 72, def: 80, speed: 75, hp: 68 },
    accentColor: "#1a1a2e",
  },
  {
    id: "wonderwoman-dc",
    name: "Wonder Woman",
    universe: "DC",
    stats: { atk: 90, def: 88, speed: 80, hp: 91 },
    accentColor: "#C41E3A",
  },
  {
    id: "theflash-dc",
    name: "The Flash",
    universe: "DC",
    stats: { atk: 70, def: 50, speed: 99, hp: 72 },
    accentColor: "#CC0000",
  },
  {
    id: "greenlantern-dc",
    name: "Green Lantern",
    universe: "DC",
    stats: { atk: 82, def: 85, speed: 78, hp: 80 },
    accentColor: "#00A550",
  },
  {
    id: "aquaman-dc",
    name: "Aquaman",
    universe: "DC",
    stats: { atk: 85, def: 78, speed: 72, hp: 88 },
    accentColor: "#F7A800",
  },
  {
    id: "cyborg-dc",
    name: "Cyborg",
    universe: "DC",
    stats: { atk: 80, def: 84, speed: 68, hp: 82 },
    accentColor: "#708090",
  },
  {
    id: "shazam-dc",
    name: "Shazam",
    universe: "DC",
    stats: { atk: 89, def: 85, speed: 85, hp: 90 },
    accentColor: "#FFD700",
  },
  {
    id: "joker-dc",
    name: "Joker",
    universe: "DC",
    stats: { atk: 55, def: 40, speed: 60, hp: 50 },
    accentColor: "#6B0AC9",
  },
  {
    id: "lexluthor-dc",
    name: "Lex Luthor",
    universe: "DC",
    stats: { atk: 65, def: 70, speed: 50, hp: 60 },
    accentColor: "#2E8B57",
  },
  {
    id: "darkseid-dc",
    name: "Darkseid",
    universe: "DC",
    stats: { atk: 98, def: 97, speed: 70, hp: 100 },
    accentColor: "#4B0082",
  },
  {
    id: "harleyquinn-dc",
    name: "Harley Quinn",
    universe: "DC",
    stats: { atk: 60, def: 45, speed: 72, hp: 55 },
    accentColor: "#FF1493",
  },
  {
    id: "blackadam-dc",
    name: "Black Adam",
    universe: "DC",
    stats: { atk: 93, def: 88, speed: 84, hp: 92 },
    accentColor: "#B8860B",
  },
  {
    id: "deathstroke-dc",
    name: "Deathstroke",
    universe: "DC",
    stats: { atk: 82, def: 76, speed: 78, hp: 74 },
    accentColor: "#808080",
  },
  {
    id: "greenarrow-dc",
    name: "Green Arrow",
    universe: "DC",
    stats: { atk: 68, def: 62, speed: 70, hp: 64 },
    accentColor: "#228B22",
  },

  // ─── Marvel ──────────────────────────────────────────────────────────
  {
    id: "ironman-marvel",
    name: "Iron Man",
    universe: "Marvel",
    stats: { atk: 85, def: 88, speed: 80, hp: 80 },
    accentColor: "#C0392B",
  },
  {
    id: "spiderman-marvel",
    name: "Spider-Man",
    universe: "Marvel",
    stats: { atk: 72, def: 65, speed: 90, hp: 70 },
    accentColor: "#E74C3C",
  },
  {
    id: "thor-marvel",
    name: "Thor",
    universe: "Marvel",
    stats: { atk: 94, def: 88, speed: 76, hp: 96 },
    accentColor: "#2980B9",
  },
  {
    id: "captainamerica-marvel",
    name: "Captain America",
    universe: "Marvel",
    stats: { atk: 74, def: 88, speed: 72, hp: 80 },
    accentColor: "#154360",
  },
  {
    id: "hulk-marvel",
    name: "Hulk",
    universe: "Marvel",
    stats: { atk: 98, def: 80, speed: 55, hp: 100 },
    accentColor: "#1E8449",
  },
  {
    id: "blackwidow-marvel",
    name: "Black Widow",
    universe: "Marvel",
    stats: { atk: 65, def: 60, speed: 84, hp: 58 },
    accentColor: "#2C3E50",
  },
  {
    id: "hawkeye-marvel",
    name: "Hawkeye",
    universe: "Marvel",
    stats: { atk: 70, def: 55, speed: 74, hp: 60 },
    accentColor: "#6C3483",
  },
  {
    id: "doctorstrange-marvel",
    name: "Doctor Strange",
    universe: "Marvel",
    stats: { atk: 88, def: 82, speed: 78, hp: 75 },
    accentColor: "#884EA0",
  },
  {
    id: "blackpanther-marvel",
    name: "Black Panther",
    universe: "Marvel",
    stats: { atk: 80, def: 82, speed: 86, hp: 78 },
    accentColor: "#1A1A2E",
  },
  {
    id: "scarletwitch-marvel",
    name: "Scarlet Witch",
    universe: "Marvel",
    stats: { atk: 94, def: 70, speed: 75, hp: 72 },
    accentColor: "#C0392B",
  },
  {
    id: "thanos-marvel",
    name: "Thanos",
    universe: "Marvel",
    stats: { atk: 97, def: 95, speed: 65, hp: 99 },
    accentColor: "#6C3483",
  },
  {
    id: "wolverine-marvel",
    name: "Wolverine",
    universe: "Marvel",
    stats: { atk: 86, def: 75, speed: 72, hp: 95 },
    accentColor: "#F39C12",
  },
  {
    id: "magneto-marvel",
    name: "Magneto",
    universe: "Marvel",
    stats: { atk: 88, def: 82, speed: 70, hp: 74 },
    accentColor: "#C0392B",
  },
  {
    id: "loki-marvel",
    name: "Loki",
    universe: "Marvel",
    stats: { atk: 78, def: 72, speed: 80, hp: 70 },
    accentColor: "#1F618D",
  },
  {
    id: "captainmarvel-marvel",
    name: "Captain Marvel",
    universe: "Marvel",
    stats: { atk: 92, def: 85, speed: 90, hp: 90 },
    accentColor: "#1F618D",
  },
  {
    id: "antman-marvel",
    name: "Ant-Man",
    universe: "Marvel",
    stats: { atk: 62, def: 60, speed: 78, hp: 58 },
    accentColor: "#E74C3C",
  },

  // ─── Anime ───────────────────────────────────────────────────────────
  {
    id: "goku-anime",
    name: "Goku",
    universe: "Anime",
    stats: { atk: 99, def: 85, speed: 96, hp: 98 },
    accentColor: "#F39C12",
  },
  {
    id: "vegeta-anime",
    name: "Vegeta",
    universe: "Anime",
    stats: { atk: 95, def: 82, speed: 92, hp: 93 },
    accentColor: "#2C3E50",
  },
  {
    id: "naruto-anime",
    name: "Naruto",
    universe: "Anime",
    stats: { atk: 88, def: 75, speed: 90, hp: 92 },
    accentColor: "#E67E22",
  },
  {
    id: "sasuke-anime",
    name: "Sasuke",
    universe: "Anime",
    stats: { atk: 90, def: 78, speed: 92, hp: 82 },
    accentColor: "#2C3E50",
  },
  {
    id: "luffy-anime",
    name: "Monkey D. Luffy",
    universe: "Anime",
    stats: { atk: 88, def: 72, speed: 85, hp: 96 },
    accentColor: "#E74C3C",
  },
  {
    id: "zoro-anime",
    name: "Roronoa Zoro",
    universe: "Anime",
    stats: { atk: 92, def: 76, speed: 80, hp: 88 },
    accentColor: "#27AE60",
  },
  {
    id: "ichigo-anime",
    name: "Ichigo Kurosaki",
    universe: "Anime",
    stats: { atk: 91, def: 78, speed: 88, hp: 87 },
    accentColor: "#E74C3C",
  },
  {
    id: "saitama-anime",
    name: "Saitama",
    universe: "Anime",
    stats: { atk: 100, def: 60, speed: 98, hp: 100 },
    accentColor: "#F39C12",
  },
  {
    id: "eren-anime",
    name: "Eren Yeager",
    universe: "Anime",
    stats: { atk: 88, def: 70, speed: 74, hp: 85 },
    accentColor: "#808080",
  },
  {
    id: "levi-anime",
    name: "Levi Ackerman",
    universe: "Anime",
    stats: { atk: 87, def: 74, speed: 97, hp: 78 },
    accentColor: "#2C3E50",
  },
  {
    id: "deku-anime",
    name: "Izuku Midoriya",
    universe: "Anime",
    stats: { atk: 85, def: 72, speed: 82, hp: 80 },
    accentColor: "#2ECC71",
  },
  {
    id: "bakugo-anime",
    name: "Katsuki Bakugo",
    universe: "Anime",
    stats: { atk: 90, def: 68, speed: 85, hp: 76 },
    accentColor: "#E74C3C",
  },
  {
    id: "allmight-anime",
    name: "All Might",
    universe: "Anime",
    stats: { atk: 97, def: 88, speed: 88, hp: 92 },
    accentColor: "#F1C40F",
  },
  {
    id: "killua-anime",
    name: "Killua Zoldyck",
    universe: "Anime",
    stats: { atk: 84, def: 70, speed: 96, hp: 74 },
    accentColor: "#85C1E9",
  },
  {
    id: "gon-anime",
    name: "Gon Freecss",
    universe: "Anime",
    stats: { atk: 82, def: 68, speed: 85, hp: 90 },
    accentColor: "#27AE60",
  },

  // ─── Other ───────────────────────────────────────────────────────────
  {
    id: "geralt-other",
    name: "Geralt of Rivia",
    universe: "Other",
    stats: { atk: 84, def: 80, speed: 74, hp: 82 },
    accentColor: "#BDC3C7",
  },
  {
    id: "masterchief-other",
    name: "Master Chief",
    universe: "Other",
    stats: { atk: 88, def: 90, speed: 70, hp: 92 },
    accentColor: "#117A65",
  },
  {
    id: "kratos-other",
    name: "Kratos",
    universe: "Other",
    stats: { atk: 97, def: 88, speed: 72, hp: 96 },
    accentColor: "#E74C3C",
  },
  {
    id: "doomslayer-other",
    name: "Doom Slayer",
    universe: "Other",
    stats: { atk: 96, def: 80, speed: 82, hp: 94 },
    accentColor: "#E74C3C",
  },
  {
    id: "link-other",
    name: "Link",
    universe: "Other",
    stats: { atk: 75, def: 78, speed: 80, hp: 76 },
    accentColor: "#27AE60",
  },
  {
    id: "cloud-other",
    name: "Cloud Strife",
    universe: "Other",
    stats: { atk: 88, def: 74, speed: 76, hp: 82 },
    accentColor: "#5DADE2",
  },
  {
    id: "aragorn-other",
    name: "Aragorn",
    universe: "Other",
    stats: { atk: 80, def: 78, speed: 70, hp: 80 },
    accentColor: "#6E2F1A",
  },
  {
    id: "arthur-other",
    name: "Arthur Morgan",
    universe: "Other",
    stats: { atk: 78, def: 72, speed: 68, hp: 80 },
    accentColor: "#7D6608",
  },
  {
    id: "aloy-other",
    name: "Aloy",
    universe: "Other",
    stats: { atk: 76, def: 70, speed: 82, hp: 74 },
    accentColor: "#E67E22",
  },
  {
    id: "jonsnow-other",
    name: "Jon Snow",
    universe: "Other",
    stats: { atk: 78, def: 76, speed: 68, hp: 76 },
    accentColor: "#2C3E50",
  },
];
